import {
  Archive,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  Ban,
  Bell,
  Bug,
  CaseSensitive,
  Check,
  CheckCheck,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronsDownUp,
  ChevronsUpDown,
  Circle,
  CircleAlert,
  CircleCheck,
  CircleDot,
  CircleX,
  Clipboard,
  Cloud,
  CloudDownload,
  CloudUpload,
  Code,
  Command,
  Copy,
  CornerDownLeft,
  Download,
  Ellipsis,
  ExternalLink,
  Eye,
  EyeOff,
  File,
  FileCode,
  FileDiff,
  FileJson,
  FilePlus,
  FileText,
  Files,
  Filter,
  Folder,
  FolderOpen,
  FolderPlus,
  GitBranch,
  GitCommitHorizontal,
  GitCompare,
  GitGraph,
  GitMerge,
  GitPullRequestArrow,
  Globe,
  Hash,
  History,
  Image,
  Info,
  KeyRound,
  Keyboard,
  Layers,
  Link,
  List,
  ListTree,
  LoaderCircle,
  Lock,
  Maximize2,
  Minimize2,
  Minus,
  Package,
  Palette,
  PanelBottom,
  PanelLeft,
  Pencil,
  Pin,
  Play,
  Plus,
  Redo2,
  Regex,
  RefreshCw,
  Replace,
  RotateCcw,
  Save,
  Search,
  Settings,
  Shield,
  ShieldAlert,
  ShieldCheck,
  SquareTerminal,
  Star,
  Tag,
  Columns2,
  Trash2,
  TriangleAlert,
  Undo2,
  Unlock,
  Upload,
  WholeWord,
  Wrench,
  X,
  type LucideIcon,
} from 'lucide-react';

/**
 * Every icon the application uses, by a short stable name. Slices refer to icons by these names
 * (quick-pick items, status bar items, menus) so the whole product shares one icon set and one
 * stroke weight. Add a name here before using a new glyph anywhere else.
 */
export const ICONS = {
  // Files and folders
  file: File,
  'file-text': FileText,
  'file-code': FileCode,
  'file-json': FileJson,
  'file-plus': FilePlus,
  'file-diff': FileDiff,
  folder: Folder,
  'folder-open': FolderOpen,
  'folder-plus': FolderPlus,
  files: Files,
  image: Image,
  package: Package,

  // Navigation and disclosure
  'chevron-right': ChevronRight,
  'chevron-down': ChevronDown,
  'chevron-up': ChevronUp,
  'chevron-left': ChevronLeft,
  'arrow-up': ArrowUp,
  'arrow-down': ArrowDown,
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  'collapse-all': ChevronsDownUp,
  'expand-all': ChevronsUpDown,
  enter: CornerDownLeft,

  // Views and chrome
  search: Search,
  'source-control': GitGraph,
  terminal: SquareTerminal,
  settings: Settings,
  'panel-left': PanelLeft,
  'panel-bottom': PanelBottom,
  split: Columns2,
  maximize: Maximize2,
  minimize: Minimize2,
  'list-tree': ListTree,
  list: List,
  layers: Layers,

  // Git
  'git-branch': GitBranch,
  'git-commit': GitCommitHorizontal,
  'git-merge': GitMerge,
  'git-compare': GitCompare,
  'git-pull-request': GitPullRequestArrow,
  'cloud-upload': CloudUpload,
  'cloud-download': CloudDownload,
  cloud: Cloud,

  // Actions
  close: X,
  plus: Plus,
  minus: Minus,
  check: Check,
  'check-all': CheckCheck,
  copy: Copy,
  trash: Trash2,
  edit: Pencil,
  eye: Eye,
  'eye-off': EyeOff,
  refresh: RefreshCw,
  more: Ellipsis,
  play: Play,
  save: Save,
  undo: Undo2,
  redo: Redo2,
  replace: Replace,
  upload: Upload,
  download: Download,
  history: History,
  clipboard: Clipboard,
  filter: Filter,
  link: Link,
  'external-link': ExternalLink,
  pin: Pin,
  archive: Archive,
  reset: RotateCcw,

  // Status
  'alert-triangle': TriangleAlert,
  'alert-circle': CircleAlert,
  'x-circle': CircleX,
  'check-circle': CircleCheck,
  info: Info,
  lock: Lock,
  unlock: Unlock,
  shield: Shield,
  'shield-alert': ShieldAlert,
  'shield-check': ShieldCheck,
  bell: Bell,
  ban: Ban,
  bug: Bug,
  circle: Circle,
  'circle-dot': CircleDot,
  loader: LoaderCircle,
  star: Star,
  tag: Tag,

  // Settings and search options
  keyboard: Keyboard,
  palette: Palette,
  command: Command,
  key: KeyRound,
  globe: Globe,
  code: Code,
  hash: Hash,
  wrench: Wrench,
  'case-sensitive': CaseSensitive,
  'whole-word': WholeWord,
  regex: Regex,
} as const satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof ICONS;

export function isIconName(name: string): name is IconName {
  return Object.prototype.hasOwnProperty.call(ICONS, name);
}

/** Alternative spellings accepted wherever an icon name is read (view ids, common synonyms). */
const ALIASES: Readonly<Record<string, IconName>> = {
  x: 'close',
  warning: 'alert-triangle',
  error: 'x-circle',
  success: 'check-circle',
  sync: 'refresh',
  ellipsis: 'more',
  explorer: 'files',
  git: 'source-control',
  scm: 'source-control',
  branch: 'git-branch',
  problems: 'alert-circle',
  gear: 'settings',
  delete: 'trash',
  rename: 'edit',
  'new-file': 'file-plus',
  'new-folder': 'folder-plus',
};

/** Resolves a name or alias to a known icon name, or undefined when there is no such icon. */
export function resolveIconName(name: string): IconName | undefined {
  if (isIconName(name)) return name;
  return ALIASES[name];
}
