import { def, type CommandDef } from './types';

/**
 * Editing, selection and editor-group commands. Owned by the editor slice.
 * Commands with `keybindingHint` are bound by Monaco itself; the hint is shown in menus only.
 */
export const EDITOR_COMMANDS: CommandDef[] = [
  // Edit menu (routed to the focused editor or text field)
  def({
    id: 'edit.undo',
    title: 'Undo',
    category: 'Edit',
    keybindingHint: 'Mod+Z',
    menu: { menu: 'Edit', group: '1_undo', order: 1 },
  }),
  def({
    id: 'edit.redo',
    title: 'Redo',
    category: 'Edit',
    keybindingHint: 'Mod+Y',
    menu: { menu: 'Edit', group: '1_undo', order: 2 },
  }),
  def({
    id: 'edit.cut',
    title: 'Cut',
    category: 'Edit',
    keybindingHint: 'Mod+X',
    menu: { menu: 'Edit', group: '2_clipboard', order: 1 },
  }),
  def({
    id: 'edit.copy',
    title: 'Copy',
    category: 'Edit',
    keybindingHint: 'Mod+C',
    menu: { menu: 'Edit', group: '2_clipboard', order: 2 },
  }),
  def({
    id: 'edit.paste',
    title: 'Paste',
    category: 'Edit',
    keybindingHint: 'Mod+V',
    menu: { menu: 'Edit', group: '2_clipboard', order: 3 },
  }),
  def({
    id: 'edit.find',
    title: 'Find',
    category: 'Edit',
    keybindingHint: 'Mod+F',
    when: 'hasActiveEditor',
    menu: { menu: 'Edit', group: '3_find', order: 1 },
  }),
  def({
    id: 'edit.replace',
    title: 'Replace',
    category: 'Edit',
    keybindingHint: 'Mod+H',
    when: 'hasActiveEditor',
    menu: { menu: 'Edit', group: '3_find', order: 2 },
  }),
  def({
    id: 'edit.toggleLineComment',
    title: 'Toggle line comment',
    category: 'Edit',
    keybindingHint: 'Mod+/',
    when: 'hasActiveEditor',
    menu: { menu: 'Edit', group: '4_comment', order: 1 },
  }),
  def({
    id: 'edit.toggleBlockComment',
    title: 'Toggle block comment',
    category: 'Edit',
    keybindingHint: 'Shift+Alt+A',
    when: 'hasActiveEditor',
    menu: { menu: 'Edit', group: '4_comment', order: 2 },
  }),
  def({
    id: 'edit.formatDocument',
    title: 'Format document',
    category: 'Edit',
    keybindingHint: 'Shift+Alt+F',
    when: 'hasActiveEditor',
    menu: { menu: 'Edit', group: '5_format', order: 1 },
  }),
  def({
    id: 'edit.formatSelection',
    title: 'Format selection',
    category: 'Edit',
    keybindingHint: 'Mod+K Mod+F',
    when: 'hasActiveEditor',
    menu: { menu: 'Edit', group: '5_format', order: 2 },
  }),
  def({
    id: 'edit.trimTrailingWhitespace',
    title: 'Trim trailing whitespace',
    category: 'Edit',
    when: 'hasActiveEditor',
  }),

  // Selection menu
  def({
    id: 'selection.selectAll',
    title: 'Select all',
    category: 'Selection',
    keybindingHint: 'Mod+A',
    menu: { menu: 'Selection', group: '1_select', order: 1 },
  }),
  def({
    id: 'selection.expand',
    title: 'Expand selection',
    category: 'Selection',
    keybindingHint: 'Shift+Alt+ArrowRight',
    when: 'hasActiveEditor',
    menu: { menu: 'Selection', group: '1_select', order: 2 },
  }),
  def({
    id: 'selection.shrink',
    title: 'Shrink selection',
    category: 'Selection',
    keybindingHint: 'Shift+Alt+ArrowLeft',
    when: 'hasActiveEditor',
    menu: { menu: 'Selection', group: '1_select', order: 3 },
  }),
  def({
    id: 'selection.copyLineUp',
    title: 'Copy line up',
    category: 'Selection',
    keybindingHint: 'Shift+Alt+ArrowUp',
    when: 'hasActiveEditor',
    menu: { menu: 'Selection', group: '2_lines', order: 1 },
  }),
  def({
    id: 'selection.copyLineDown',
    title: 'Copy line down',
    category: 'Selection',
    keybindingHint: 'Shift+Alt+ArrowDown',
    when: 'hasActiveEditor',
    menu: { menu: 'Selection', group: '2_lines', order: 2 },
  }),
  def({
    id: 'selection.moveLineUp',
    title: 'Move line up',
    category: 'Selection',
    keybindingHint: 'Alt+ArrowUp',
    when: 'hasActiveEditor',
    menu: { menu: 'Selection', group: '2_lines', order: 3 },
  }),
  def({
    id: 'selection.moveLineDown',
    title: 'Move line down',
    category: 'Selection',
    keybindingHint: 'Alt+ArrowDown',
    when: 'hasActiveEditor',
    menu: { menu: 'Selection', group: '2_lines', order: 4 },
  }),
  def({
    id: 'selection.addCursorAbove',
    title: 'Add cursor above',
    category: 'Selection',
    keybindingHint: 'Mod+Alt+ArrowUp',
    when: 'hasActiveEditor',
    menu: { menu: 'Selection', group: '3_cursors', order: 1 },
  }),
  def({
    id: 'selection.addCursorBelow',
    title: 'Add cursor below',
    category: 'Selection',
    keybindingHint: 'Mod+Alt+ArrowDown',
    when: 'hasActiveEditor',
    menu: { menu: 'Selection', group: '3_cursors', order: 2 },
  }),
  def({
    id: 'selection.addNextOccurrence',
    title: 'Add next occurrence',
    category: 'Selection',
    keybindingHint: 'Mod+D',
    when: 'hasActiveEditor',
    menu: { menu: 'Selection', group: '3_cursors', order: 3 },
  }),
  def({
    id: 'selection.selectAllOccurrences',
    title: 'Select all occurrences',
    category: 'Selection',
    keybindingHint: 'Mod+Shift+L',
    when: 'hasActiveEditor',
    menu: { menu: 'Selection', group: '3_cursors', order: 4 },
  }),

  // Go (editor-scoped)
  def({
    id: 'go.definition',
    title: 'Go to definition',
    category: 'Go',
    keybindingHint: 'F12',
    when: 'hasActiveEditor',
    menu: { menu: 'Go', group: '4_symbols', order: 1 },
  }),
  def({
    id: 'go.references',
    title: 'Go to references',
    category: 'Go',
    keybindingHint: 'Shift+F12',
    when: 'hasActiveEditor',
    menu: { menu: 'Go', group: '4_symbols', order: 2 },
  }),

  // Tabs and groups
  def({
    id: 'editor.nextTab',
    title: 'Next editor',
    category: 'Editor',
    keybinding: { key: 'Ctrl+PageDown' },
    when: 'hasActiveEditor',
  }),
  def({
    id: 'editor.previousTab',
    title: 'Previous editor',
    category: 'Editor',
    keybinding: { key: 'Ctrl+PageUp' },
    when: 'hasActiveEditor',
  }),
  def({
    id: 'editor.nextRecentTab',
    title: 'Next recently used editor',
    category: 'Editor',
    keybinding: { key: 'Ctrl+Tab' },
    when: 'hasActiveEditor',
    palette: false,
  }),
  def({
    id: 'editor.previousRecentTab',
    title: 'Previous recently used editor',
    category: 'Editor',
    keybinding: { key: 'Ctrl+Shift+Tab' },
    when: 'hasActiveEditor',
    palette: false,
  }),
  def({
    id: 'editor.reopenClosed',
    title: 'Reopen closed editor',
    category: 'Editor',
    keybinding: { key: 'Mod+Shift+T' },
    menu: { menu: 'File', group: '4_close', order: 4 },
  }),
  def({
    id: 'editor.closeOthers',
    title: 'Close other editors',
    category: 'Editor',
    when: 'hasActiveEditor',
  }),
  def({
    id: 'editor.closeSaved',
    title: 'Close saved editors',
    category: 'Editor',
    when: 'hasActiveEditor',
  }),
  def({
    id: 'editor.pinTab',
    title: 'Keep editor open',
    category: 'Editor',
    when: 'hasActiveEditor',
  }),
  def({
    id: 'editor.splitRight',
    title: 'Split editor right',
    category: 'View',
    keybinding: { key: 'Mod+\\' },
    when: 'hasActiveEditor',
    menu: { menu: 'View', group: '5_editor', order: 1 },
  }),
  def({
    id: 'editor.closeGroup',
    title: 'Close editor group',
    category: 'Editor',
    when: 'hasActiveEditor',
  }),
  def({
    id: 'editor.focusFirstGroup',
    title: 'Focus first editor group',
    category: 'View',
    keybinding: { key: 'Mod+1' },
    menu: { menu: 'View', group: '5_editor', order: 2 },
  }),
  def({
    id: 'editor.focusSecondGroup',
    title: 'Focus second editor group',
    category: 'View',
    keybinding: { key: 'Mod+2' },
    menu: { menu: 'View', group: '5_editor', order: 3 },
  }),
  def({
    id: 'editor.moveToOtherGroup',
    title: 'Move editor to other group',
    category: 'Editor',
    keybinding: { key: 'Mod+K ArrowRight' },
    when: 'hasActiveEditor',
  }),
  def({
    id: 'editor.toggleWordWrap',
    title: 'Toggle word wrap',
    category: 'View',
    keybinding: { key: 'Alt+Z' },
    when: 'hasActiveEditor',
    menu: { menu: 'View', group: '5_editor', order: 4 },
  }),
  def({
    id: 'editor.toggleMinimap',
    title: 'Toggle minimap',
    category: 'View',
    when: 'hasActiveEditor',
    menu: { menu: 'View', group: '5_editor', order: 5 },
  }),
  def({
    id: 'editor.copyPath',
    title: 'Copy path of active file',
    category: 'File',
    keybinding: { key: 'Shift+Alt+C' },
    when: 'hasActiveEditor',
  }),
  def({
    id: 'editor.copyRelativePath',
    title: 'Copy relative path of active file',
    category: 'File',
    keybinding: { key: 'Mod+K Mod+Shift+C' },
    when: 'hasActiveEditor',
  }),
  def({
    id: 'editor.revealInExplorer',
    title: 'Reveal active file in explorer',
    category: 'File',
    when: 'hasActiveEditor && hasWorkspace',
  }),
  def({
    id: 'editor.revealInOS',
    title: 'Reveal active file in file manager',
    category: 'File',
    when: 'hasActiveEditor',
  }),

  // Status bar pickers
  def({
    id: 'editor.changeLanguage',
    title: 'Change language mode',
    category: 'Editor',
    keybinding: { key: 'Mod+K M' },
    when: 'hasActiveEditor',
  }),
  def({
    id: 'editor.changeEol',
    title: 'Change end of line sequence',
    category: 'Editor',
    when: 'hasActiveEditor',
  }),
  def({
    id: 'editor.changeEncoding',
    title: 'Change file encoding',
    category: 'Editor',
    when: 'hasActiveEditor',
  }),
  def({
    id: 'editor.reopenWithEncoding',
    title: 'Reopen with encoding...',
    category: 'Editor',
    when: 'hasActiveEditor',
  }),
  def({
    id: 'editor.changeIndentation',
    title: 'Change indentation',
    category: 'Editor',
    when: 'hasActiveEditor',
  }),
  def({
    id: 'editor.openChanges',
    title: 'Open changes with HEAD',
    category: 'Git',
    when: 'hasActiveEditor && gitAvailable',
  }),
];
