import { def, type CommandDef } from './types';

/** Explorer, search and source control commands. Owned by their respective slices. */
export const SIDEBAR_COMMANDS: CommandDef[] = [
  // Explorer
  def({
    id: 'explorer.newFile',
    title: 'New file in explorer',
    category: 'Explorer',
    when: 'hasWorkspace',
  }),
  def({
    id: 'explorer.newFolder',
    title: 'New folder',
    category: 'Explorer',
    when: 'hasWorkspace',
  }),
  def({
    id: 'explorer.rename',
    title: 'Rename',
    category: 'Explorer',
    keybinding: { key: 'F2', mac: 'Enter', when: 'explorerFocus && !inputFocus' },
    palette: false,
  }),
  def({
    id: 'explorer.delete',
    title: 'Delete',
    category: 'Explorer',
    keybinding: { key: 'Delete', mac: 'Cmd+Backspace', when: 'explorerFocus && !inputFocus' },
    palette: false,
  }),
  def({
    id: 'explorer.copy',
    title: 'Copy',
    category: 'Explorer',
    keybinding: { key: 'Mod+C', when: 'explorerFocus && !inputFocus' },
    palette: false,
  }),
  def({
    id: 'explorer.cut',
    title: 'Cut',
    category: 'Explorer',
    keybinding: { key: 'Mod+X', when: 'explorerFocus && !inputFocus' },
    palette: false,
  }),
  def({
    id: 'explorer.paste',
    title: 'Paste',
    category: 'Explorer',
    keybinding: { key: 'Mod+V', when: 'explorerFocus && !inputFocus' },
    palette: false,
  }),
  def({ id: 'explorer.duplicate', title: 'Duplicate', category: 'Explorer', palette: false }),
  def({
    id: 'explorer.refresh',
    title: 'Refresh explorer',
    category: 'Explorer',
    when: 'hasWorkspace',
  }),
  def({
    id: 'explorer.collapseAll',
    title: 'Collapse all folders',
    category: 'Explorer',
    when: 'hasWorkspace',
  }),
  def({
    id: 'explorer.copyPath',
    title: 'Copy path',
    category: 'Explorer',
    keybinding: { key: 'Shift+Alt+C', when: 'explorerFocus && !inputFocus' },
    palette: false,
  }),
  def({
    id: 'explorer.copyRelativePath',
    title: 'Copy relative path',
    category: 'Explorer',
    palette: false,
  }),
  def({
    id: 'explorer.revealInOS',
    title: 'Reveal in file manager',
    category: 'Explorer',
    keybinding: { key: 'Shift+Alt+R', when: 'explorerFocus && !inputFocus' },
    palette: false,
  }),
  def({ id: 'explorer.reveal', title: 'Reveal in explorer', category: 'Explorer', palette: false }),
  def({
    id: 'explorer.openToSide',
    title: 'Open to the side',
    category: 'Explorer',
    keybinding: { key: 'Mod+Enter', when: 'explorerFocus && !inputFocus' },
    palette: false,
  }),
  def({
    id: 'explorer.findInFolder',
    title: 'Find in folder...',
    category: 'Explorer',
    palette: false,
  }),

  // Search
  def({
    id: 'search.findInFiles',
    title: 'Find in files',
    category: 'Search',
    keybinding: { key: 'Mod+Shift+F' },
    when: 'hasWorkspace',
    menu: { menu: 'Edit', group: '3_find', order: 3 },
  }),
  def({
    id: 'search.replaceInFiles',
    title: 'Replace in files',
    category: 'Search',
    keybinding: { key: 'Mod+Shift+H' },
    when: 'hasWorkspace',
    menu: { menu: 'Edit', group: '3_find', order: 4 },
  }),
  def({ id: 'search.clearResults', title: 'Clear search results', category: 'Search' }),
  def({
    id: 'search.collapseAll',
    title: 'Collapse all search results',
    category: 'Search',
    palette: false,
  }),

  // Source control
  def({ id: 'git.refresh', title: 'Refresh', category: 'Git', when: 'gitAvailable' }),
  def({
    id: 'git.init',
    title: 'Initialize repository',
    category: 'Git',
    when: 'hasWorkspace && !gitRepo',
  }),
  def({ id: 'git.stageAll', title: 'Stage all changes', category: 'Git', when: 'gitRepo' }),
  def({ id: 'git.unstageAll', title: 'Unstage all changes', category: 'Git', when: 'gitRepo' }),
  def({
    id: 'git.commit',
    title: 'Commit staged changes',
    category: 'Git',
    keybinding: { key: 'Mod+Enter', when: 'scmFocus' },
    when: 'gitRepo',
  }),
  def({ id: 'git.commitAmend', title: 'Commit (amend)', category: 'Git', when: 'gitRepo' }),
  def({ id: 'git.checkout', title: 'Checkout to...', category: 'Git', when: 'gitRepo' }),
  def({ id: 'git.createBranch', title: 'Create branch...', category: 'Git', when: 'gitRepo' }),
  def({ id: 'git.fetch', title: 'Fetch', category: 'Git', when: 'gitRepo' }),
  def({ id: 'git.pull', title: 'Pull', category: 'Git', when: 'gitRepo' }),
  def({ id: 'git.push', title: 'Push', category: 'Git', when: 'gitRepo' }),
  def({ id: 'git.openDiff', title: 'Open changes', category: 'Git', palette: false }),
  def({ id: 'git.stage', title: 'Stage changes', category: 'Git', palette: false }),
  def({ id: 'git.unstage', title: 'Unstage changes', category: 'Git', palette: false }),
  def({ id: 'git.discard', title: 'Discard changes', category: 'Git', palette: false }),
  def({
    id: 'git.showFileHistory',
    title: 'Show history of active file',
    category: 'Git',
    when: 'gitRepo && hasActiveEditor',
  }),
];
