import { def, type CommandDef } from './types';

/** Window, file-level, view and help commands. Owned by the shell and workbench layout slices. */
export const WORKBENCH_COMMANDS: CommandDef[] = [
  // File
  def({
    id: 'file.newFile',
    title: 'New file',
    category: 'File',
    keybinding: { key: 'Mod+N' },
    menu: { menu: 'File', group: '1_new', order: 1 },
  }),
  def({
    id: 'file.newWindow',
    title: 'New window',
    category: 'File',
    keybinding: { key: 'Mod+Shift+N' },
    menu: { menu: 'File', group: '1_new', order: 2 },
  }),
  def({
    id: 'file.openFile',
    title: 'Open file...',
    category: 'File',
    keybinding: { key: 'Mod+O' },
    menu: { menu: 'File', group: '2_open', order: 1 },
  }),
  def({
    id: 'file.openFolder',
    title: 'Open folder...',
    category: 'File',
    keybinding: { key: 'Mod+K Mod+O' },
    menu: { menu: 'File', group: '2_open', order: 2 },
  }),
  def({
    id: 'file.openRecent',
    title: 'Open recent...',
    category: 'File',
    keybinding: { key: 'Mod+R' },
    menu: { menu: 'File', group: '2_open', order: 3 },
  }),
  def({
    id: 'file.closeFolder',
    title: 'Close folder',
    category: 'File',
    when: 'hasWorkspace',
    menu: { menu: 'File', group: '2_open', order: 4 },
  }),
  def({
    id: 'file.save',
    title: 'Save',
    category: 'File',
    keybinding: { key: 'Mod+S' },
    when: 'hasActiveEditor',
    menu: { menu: 'File', group: '3_save', order: 1 },
  }),
  def({
    id: 'file.saveAs',
    title: 'Save as...',
    category: 'File',
    keybinding: { key: 'Mod+Shift+S' },
    when: 'hasActiveEditor',
    menu: { menu: 'File', group: '3_save', order: 2 },
  }),
  def({
    id: 'file.saveAll',
    title: 'Save all',
    category: 'File',
    keybinding: { key: 'Mod+K S' },
    when: 'hasDirtyEditors',
    menu: { menu: 'File', group: '3_save', order: 3 },
  }),
  def({
    id: 'file.revert',
    title: 'Revert file',
    category: 'File',
    when: 'hasActiveEditor',
    menu: { menu: 'File', group: '3_save', order: 4 },
  }),
  def({
    id: 'file.closeEditor',
    title: 'Close editor',
    category: 'File',
    keybinding: { key: 'Mod+W' },
    when: 'hasActiveEditor',
    menu: { menu: 'File', group: '4_close', order: 1 },
  }),
  def({
    id: 'file.closeAllEditors',
    title: 'Close all editors',
    category: 'File',
    keybinding: { key: 'Mod+K W' },
    when: 'hasActiveEditor',
    menu: { menu: 'File', group: '4_close', order: 2 },
  }),
  def({
    id: 'file.closeWindow',
    title: 'Close window',
    category: 'File',
    keybinding: { key: 'Alt+F4', mac: 'Cmd+Shift+W' },
    menu: { menu: 'File', group: '4_close', order: 3 },
  }),
  def({
    id: 'file.exit',
    title: 'Exit',
    category: 'File',
    keybinding: { key: 'Mod+Q', mac: 'Cmd+Q' },
    menu: { menu: 'File', group: '9_exit', order: 1 },
  }),

  // View
  def({
    id: 'palette.commands',
    title: 'Show all commands',
    category: 'View',
    keybinding: { key: 'Mod+Shift+P' },
    menu: { menu: 'View', group: '1_palette', order: 1 },
    palette: false,
  }),
  def({
    id: 'view.showExplorer',
    title: 'Show explorer',
    category: 'View',
    keybinding: { key: 'Mod+Shift+E' },
    menu: { menu: 'View', group: '2_views', order: 1 },
  }),
  def({
    id: 'view.showSearch',
    title: 'Show search',
    category: 'View',
    menu: { menu: 'View', group: '2_views', order: 2 },
  }),
  def({
    id: 'view.showGit',
    title: 'Show source control',
    category: 'View',
    keybinding: { key: 'Mod+Shift+G', mac: 'Ctrl+Shift+G' },
    menu: { menu: 'View', group: '2_views', order: 3 },
  }),
  def({
    id: 'view.showProblems',
    title: 'Show problems',
    category: 'View',
    keybinding: { key: 'Mod+Shift+M' },
    menu: { menu: 'View', group: '2_views', order: 4 },
  }),
  def({
    id: 'view.toggleSidebar',
    title: 'Toggle sidebar',
    category: 'View',
    keybinding: { key: 'Mod+B' },
    menu: { menu: 'View', group: '3_layout', order: 1 },
  }),
  def({
    id: 'view.toggleBottomPanel',
    title: 'Toggle bottom panel',
    category: 'View',
    keybinding: { key: 'Mod+J' },
    menu: { menu: 'View', group: '3_layout', order: 2 },
  }),
  def({
    id: 'view.toggleFullscreen',
    title: 'Toggle full screen',
    category: 'View',
    keybinding: { key: 'F11', mac: 'Ctrl+Cmd+F' },
    menu: { menu: 'View', group: '3_layout', order: 3 },
  }),
  def({
    id: 'view.zoomIn',
    title: 'Zoom in',
    category: 'View',
    keybinding: { key: 'Mod+=' },
    menu: { menu: 'View', group: '4_zoom', order: 1 },
  }),
  def({
    id: 'view.zoomOut',
    title: 'Zoom out',
    category: 'View',
    keybinding: { key: 'Mod+-' },
    menu: { menu: 'View', group: '4_zoom', order: 2 },
  }),
  def({
    id: 'view.zoomReset',
    title: 'Reset zoom',
    category: 'View',
    keybinding: { key: 'Mod+0' },
    menu: { menu: 'View', group: '4_zoom', order: 3 },
  }),
  def({
    id: 'view.reload',
    title: 'Reload window',
    category: 'View',
    menu: { menu: 'View', group: '9_dev', order: 1 },
  }),

  // Go
  def({
    id: 'palette.quickOpen',
    title: 'Go to file...',
    category: 'Go',
    keybinding: { key: 'Mod+P' },
    menu: { menu: 'Go', group: '1_goto', order: 1 },
  }),
  def({
    id: 'palette.gotoLine',
    title: 'Go to line...',
    category: 'Go',
    keybinding: { key: 'Mod+G', mac: 'Ctrl+G' },
    when: 'hasActiveEditor',
    menu: { menu: 'Go', group: '1_goto', order: 2 },
  }),
  def({
    id: 'palette.gotoSymbol',
    title: 'Go to symbol in file...',
    category: 'Go',
    keybinding: { key: 'Mod+Shift+O' },
    when: 'hasActiveEditor',
    menu: { menu: 'Go', group: '1_goto', order: 3 },
  }),
  def({
    id: 'go.back',
    title: 'Go back',
    category: 'Go',
    keybinding: { key: 'Alt+ArrowLeft', mac: 'Ctrl+-' },
    menu: { menu: 'Go', group: '2_nav', order: 1 },
  }),
  def({
    id: 'go.forward',
    title: 'Go forward',
    category: 'Go',
    keybinding: { key: 'Alt+ArrowRight', mac: 'Ctrl+Shift+-' },
    menu: { menu: 'Go', group: '2_nav', order: 2 },
  }),
  def({
    id: 'go.nextProblem',
    title: 'Go to next problem',
    category: 'Go',
    keybinding: { key: 'F8' },
    when: 'hasActiveEditor',
    menu: { menu: 'Go', group: '3_problems', order: 1 },
  }),
  def({
    id: 'go.previousProblem',
    title: 'Go to previous problem',
    category: 'Go',
    keybinding: { key: 'Shift+F8' },
    when: 'hasActiveEditor',
    menu: { menu: 'Go', group: '3_problems', order: 2 },
  }),

  // Help
  def({
    id: 'help.about',
    title: 'About .inc',
    category: 'Help',
    menu: { menu: 'Help', group: '1_about', order: 1 },
  }),
  def({
    id: 'help.shortcuts',
    title: 'Keyboard shortcuts reference',
    category: 'Help',
    menu: { menu: 'Help', group: '2_docs', order: 1 },
  }),
  def({
    id: 'help.thirdPartyNotices',
    title: 'Third-party notices',
    category: 'Help',
    menu: { menu: 'Help', group: '2_docs', order: 2 },
  }),
  def({
    id: 'help.showLogs',
    title: 'Show logs folder',
    category: 'Help',
    menu: { menu: 'Help', group: '3_support', order: 1 },
  }),
  def({
    id: 'help.copyDiagnostics',
    title: 'Copy diagnostics',
    category: 'Help',
    menu: { menu: 'Help', group: '3_support', order: 2 },
  }),
  def({
    id: 'help.toggleDevTools',
    title: 'Toggle developer tools',
    category: 'Help',
    keybinding: { key: 'Mod+Shift+I', mac: 'Cmd+Alt+I' },
    menu: { menu: 'Help', group: '4_dev', order: 1 },
  }),
];
