// Generates docs/SETTINGS.md and docs/KEYBINDINGS.md from the real settings schema and command
// catalog, so the reference cannot drift from the app.
//
//   node scripts/gen-docs.mjs           write both files
//   node scripts/gen-docs.mjs --check   fail if either file is out of date (does not write)
import { build } from 'esbuild';
import { mkdtemp, readFile, rm, writeFile } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { pathToFileURL } from 'node:url';

const root = path.resolve(import.meta.dirname, '..');
const check = process.argv.includes('--check');

async function load(entry) {
  const dir = await mkdtemp(path.join(os.tmpdir(), 'inc-docs-'));
  const outfile = path.join(dir, 'bundle.mjs');
  try {
    await build({
      entryPoints: [path.join(root, entry)],
      outfile,
      bundle: true,
      format: 'esm',
      platform: 'node',
      logLevel: 'silent',
    });
    return await import(pathToFileURL(outfile).href);
  } finally {
    await rm(dir, { recursive: true, force: true });
  }
}

const cell = (text) => String(text).replace(/\|/g, '\\|').replace(/\r?\n/g, ' ');
const code = (value) => '`' + JSON.stringify(value) + '`';

function settingsDoc({ SETTINGS, SETTING_CATEGORIES }) {
  const lines = [
    '# Settings reference',
    '',
    'Generated by `npm run docs` from the settings schema. Do not edit by hand.',
    '',
    'Settings are layered. From lowest to highest priority: built-in defaults, your user `settings.json`, the workspace file `<folder>/.inc/settings.json`, and the enterprise policy file (see [ADMIN.md](ADMIN.md)). A setting marked *workspace* may be overridden per folder. A setting marked *restricted* is ignored from a workspace until the folder is trusted.',
    '',
  ];
  const defs = Object.values(SETTINGS);
  for (const category of SETTING_CATEGORIES) {
    const rows = defs.filter((d) => d.category === category);
    if (rows.length === 0) continue;
    lines.push(
      `## ${category}`,
      '',
      '| Setting | Type | Default | Description |',
      '| --- | --- | --- | --- |',
    );
    for (const d of rows) {
      const flags = [
        d.scope === 'workspace' ? 'workspace' : null,
        d.restricted ? 'restricted' : null,
      ]
        .filter(Boolean)
        .join(', ');
      const range =
        d.minimum !== undefined || d.maximum !== undefined
          ? ` (${d.minimum ?? ''}–${d.maximum ?? ''})`
          : '';
      const values = d.enum ? ` One of: ${d.enum.map((v) => '`' + v + '`').join(', ')}.` : '';
      lines.push(
        `| \`${d.key}\` | ${d.type}${range} | ${cell(code(d.default))} | ${cell(d.description)}${cell(values)}${flags ? ` *(${flags})*` : ''} |`,
      );
    }
    lines.push('');
  }
  return lines.join('\n');
}

function keybindingsDoc({ COMMANDS }) {
  const lines = [
    '# Keyboard shortcuts',
    '',
    'Generated by `npm run docs` from the command catalog. Do not edit by hand.',
    '',
    'Open the Keyboard shortcuts editor from the command palette to change any shortcut, or edit `keybindings.json` in the user data folder. `Mod` is Ctrl on Windows and Linux and Cmd on macOS. A macOS column entry replaces the shortcut on macOS only. A space separates the two steps of a chord.',
    '',
    '| Command | Shortcut | macOS | When |',
    '| --- | --- | --- | --- |',
  ];
  const bound = COMMANDS.filter((c) => c.keybinding || c.keybindingHint).sort((a, b) =>
    `${a.category ?? ''}${a.title}`.localeCompare(`${b.category ?? ''}${b.title}`),
  );
  for (const c of bound) {
    const title = c.category ? `${c.category}: ${c.title}` : c.title;
    const key = c.keybinding?.key ?? c.keybindingHint ?? '';
    const mac = c.keybinding?.mac ?? '';
    lines.push(
      `| ${cell(title)} (\`${c.id}\`) | ${cell(key)} | ${cell(mac)} | ${cell(c.keybinding?.when ?? '')} |`,
    );
  }
  lines.push('');
  return lines.join('\n');
}

const targets = [
  ['docs/SETTINGS.md', settingsDoc(await load('src/shared/settings.ts'))],
  ['docs/KEYBINDINGS.md', keybindingsDoc(await load('src/shared/commands/catalog.ts'))],
];

let stale = false;
for (const [file, content] of targets) {
  const full = path.join(root, file);
  const current = await readFile(full, 'utf8').catch(() => null);
  if (current === content) continue;
  if (check) {
    console.error(`${file} is out of date. Run: npm run docs`);
    stale = true;
  } else {
    await writeFile(full, content);
    console.log(`Wrote ${file}`);
  }
}
if (stale) process.exit(1);
if (check) console.log('Generated docs are up to date.');
