/*
  .inc Monaco themes - generated from src/renderer/styles/tokens.css.
  Monaco cannot read CSS custom properties, so every colour here is a hex
  literal that mirrors the token of the same role. When a token changes,
  update the matching value here (the contrast report covers both).
  Colours are #rrggbb or #rrggbbaa.
*/
import type { editor } from 'monaco-editor';

export type IncThemeName = 'inc-light' | 'inc-dark' | 'inc-hc-light' | 'inc-hc-dark';

export const incThemes: Record<
  'inc-light' | 'inc-dark' | 'inc-hc-light' | 'inc-hc-dark',
  editor.IStandaloneThemeData
> = {
  'inc-light': {
    base: 'vs',
    inherit: false,
    rules: [
      { token: '', foreground: '1b2330' },
      { token: 'comment', foreground: '535f6d', fontStyle: 'italic' },
      { token: 'comment.doc', foreground: '535f6d', fontStyle: 'italic' },
      { token: 'keyword', foreground: '4f3fc2' },
      { token: 'keyword.control', foreground: '4f3fc2' },
      { token: 'keyword.operator', foreground: '465264' },
      { token: 'storage', foreground: '4f3fc2' },
      { token: 'storage.type', foreground: '4f3fc2' },
      { token: 'string', foreground: '3d6b17' },
      { token: 'string.escape', foreground: 'a0401d' },
      { token: 'string.invalid', foreground: 'b3261e' },
      { token: 'number', foreground: '8f4d0f' },
      { token: 'number.hex', foreground: '8f4d0f' },
      { token: 'number.float', foreground: '8f4d0f' },
      { token: 'number.octal', foreground: '8f4d0f' },
      { token: 'number.binary', foreground: '8f4d0f' },
      { token: 'regexp', foreground: 'a0401d' },
      { token: 'regexp.escape', foreground: '8f4d0f' },
      { token: 'regexp.escape.control', foreground: '4f3fc2' },
      { token: 'type', foreground: '9a3475' },
      { token: 'type.identifier', foreground: '9a3475' },
      { token: 'entity.name.type', foreground: '9a3475' },
      { token: 'entity.name.class', foreground: '9a3475' },
      { token: 'entity.name.function', foreground: '09666e' },
      { token: 'function', foreground: '09666e' },
      { token: 'support.function', foreground: '09666e' },
      { token: 'identifier', foreground: '263041' },
      { token: 'variable', foreground: '263041' },
      { token: 'variable.predefined', foreground: 'a0401d' },
      { token: 'variable.parameter', foreground: '263041' },
      { token: 'constant', foreground: 'a0401d' },
      { token: 'constant.language', foreground: 'a0401d' },
      { token: 'predefined', foreground: 'a0401d' },
      { token: 'operator', foreground: '465264' },
      { token: 'delimiter', foreground: '535f70' },
      { token: 'delimiter.bracket', foreground: '535f70' },
      { token: 'delimiter.parenthesis', foreground: '535f70' },
      { token: 'delimiter.square', foreground: '535f70' },
      { token: 'delimiter.curly', foreground: '535f70' },
      { token: 'delimiter.angle', foreground: '535f70' },
      { token: 'tag', foreground: '1a5bb8' },
      { token: 'metatag', foreground: '1a5bb8' },
      { token: 'attribute.name', foreground: '81550a' },
      { token: 'attribute.value', foreground: '3d6b17' },
      { token: 'annotation', foreground: '81550a' },
      { token: 'invalid', foreground: 'b3261e', fontStyle: 'underline' },
      { token: 'string.key.json', foreground: '81550a' },
      { token: 'string.value.json', foreground: '3d6b17' },
      { token: 'number.json', foreground: '8f4d0f' },
      { token: 'keyword.json', foreground: 'a0401d' },
      { token: 'delimiter.bracket.json', foreground: '535f70' },
      { token: 'delimiter.array.json', foreground: '535f70' },
      { token: 'delimiter.colon.json', foreground: '535f70' },
      { token: 'delimiter.comma.json', foreground: '535f70' },
      { token: 'tag.css', foreground: '1a5bb8' },
      { token: 'tag.id.css', foreground: '9a3475' },
      { token: 'tag.class.css', foreground: '9a3475' },
      { token: 'attribute.name.css', foreground: '81550a' },
      { token: 'attribute.value.css', foreground: '3d6b17' },
      { token: 'attribute.value.number.css', foreground: '8f4d0f' },
      { token: 'attribute.value.unit.css', foreground: '8f4d0f' },
      { token: 'attribute.value.hex.css', foreground: '8f4d0f' },
      { token: 'keyword.css', foreground: '4f3fc2' },
      { token: 'string.css', foreground: '3d6b17' },
      { token: 'delimiter.css', foreground: '535f70' },
      { token: 'variable.scss', foreground: '263041' },
      { token: 'tag.html', foreground: '1a5bb8' },
      { token: 'delimiter.html', foreground: '535f70' },
      { token: 'attribute.name.html', foreground: '81550a' },
      { token: 'attribute.value.html', foreground: '3d6b17' },
      { token: 'metatag.html', foreground: '1a5bb8' },
      { token: 'metatag.content.html', foreground: '3d6b17' },
      { token: 'comment.html', foreground: '535f6d', fontStyle: 'italic' },
      { token: 'keyword.md', foreground: '4f3fc2', fontStyle: 'bold' },
      { token: 'markup.heading', foreground: '4f3fc2', fontStyle: 'bold' },
      { token: 'markup.heading.md', foreground: '4f3fc2', fontStyle: 'bold' },
      { token: 'string.md', foreground: '263041' },
      { token: 'strong', foreground: '1b2330', fontStyle: 'bold' },
      { token: 'emphasis', foreground: '1b2330', fontStyle: 'italic' },
      { token: 'markup.bold', foreground: '1b2330', fontStyle: 'bold' },
      { token: 'markup.italic', foreground: '1b2330', fontStyle: 'italic' },
      { token: 'markup.inline.raw', foreground: '3d6b17' },
      { token: 'string.link.md', foreground: '1a56c0', fontStyle: 'underline' },
      { token: 'variable.source.md', foreground: '3d6b17' },
      { token: 'variable.md', foreground: '3d6b17' },
      { token: 'meta.separator', foreground: '535f70' },
      { token: 'meta.tag', foreground: '1a5bb8' },
      { token: 'predefined.sql', foreground: '09666e' },
      { token: 'operator.sql', foreground: '465264' },
      { token: 'key', foreground: '81550a' },
      { token: 'keyword.yaml', foreground: 'a0401d' },
    ],
    colors: {
      focusBorder: '#1f5fd1',
      foreground: '#1b2330',
      descriptionForeground: '#445062',
      errorForeground: '#b3261e',
      'widget.shadow': '#00000000',
      'textLink.foreground': '#1a56c0',
      'textLink.activeForeground': '#1a56c0',
      'textCodeBlock.background': '#ffffff',
      'editor.background': '#f8f9fb',
      'editor.foreground': '#1b2330',
      'editor.lineHighlightBackground': '#1b23300b',
      'editor.lineHighlightBorder': '#00000000',
      'editor.selectionBackground': '#1f5fd133',
      'editor.inactiveSelectionBackground': '#1b23301a',
      'editor.selectionHighlightBackground': '#1f5fd11a',
      'editor.wordHighlightBackground': '#1b23301a',
      'editor.wordHighlightStrongBackground': '#1f5fd133',
      'editor.findMatchBackground': '#d6961457',
      'editor.findMatchHighlightBackground': '#d6961430',
      'editor.findRangeHighlightBackground': '#1b23300b',
      'editor.hoverHighlightBackground': '#1b23300e',
      'editor.rangeHighlightBackground': '#1b23300b',
      'editor.symbolHighlightBackground': '#1f5fd133',
      'editor.foldBackground': '#1b23300b',
      'editorBracketMatch.background': '#1f5fd133',
      'editorBracketMatch.border': '#00000000',
      'editorCursor.foreground': '#1b2330',
      'editorCursor.background': '#f8f9fb',
      'editorLineNumber.foreground': '#66727f',
      'editorLineNumber.activeForeground': '#1b2330',
      'editorIndentGuide.background': '#1b23301f',
      'editorIndentGuide.activeBackground': '#1b233052',
      'editorIndentGuide.background1': '#1b23301f',
      'editorIndentGuide.activeBackground1': '#1b233052',
      'editorWhitespace.foreground': '#1b23301f',
      'editorRuler.foreground': '#1b23301f',
      'editorLink.activeForeground': '#1a56c0',
      'editorCodeLens.foreground': '#5a6677',
      'editorInlayHint.foreground': '#5a6677',
      'editorInlayHint.background': '#1b23300e',
      'editorGhostText.foreground': '#5a6677',
      'editorUnnecessaryCode.opacity': '#000000a0',
      'editorStickyScroll.background': '#f8f9fb',
      'editorStickyScrollHover.background': '#1b23300e',
      'editorGutter.background': '#f8f9fb',
      'editorGutter.addedBackground': '#1f6a3a',
      'editorGutter.modifiedBackground': '#775709',
      'editorGutter.deletedBackground': '#a3373a',
      'editorGutter.foldingControlForeground': '#445062',
      'editorError.foreground': '#b3261e',
      'editorWarning.foreground': '#8a5a00',
      'editorInfo.foreground': '#1a5bb8',
      'editorHint.foreground': '#5a6677',
      'editorError.border': '#00000000',
      'editorWarning.border': '#00000000',
      'editorInfo.border': '#00000000',
      'diffEditor.insertedTextBackground': '#23703f1f',
      'diffEditor.removedTextBackground': '#ab3b3d1f',
      'diffEditor.insertedLineBackground': '#23703f10',
      'diffEditor.removedLineBackground': '#ab3b3d10',
      'diffEditor.border': '#dbe0e6',
      'diffEditor.diagonalFill': '#1b23301f',
      'diffEditorGutter.insertedLineBackground': '#23703f1f',
      'diffEditorGutter.removedLineBackground': '#ab3b3d1f',
      'editorWidget.background': '#ffffff',
      'editorWidget.foreground': '#1b2330',
      'editorWidget.border': '#dbe0e6',
      'editorWidget.resizeBorder': '#1f5fd1',
      'editorSuggestWidget.background': '#ffffff',
      'editorSuggestWidget.foreground': '#1b2330',
      'editorSuggestWidget.border': '#dbe0e6',
      'editorSuggestWidget.selectedBackground': '#1f5fd12e',
      'editorSuggestWidget.selectedForeground': '#1b2330',
      'editorSuggestWidget.highlightForeground': '#1a56c0',
      'editorSuggestWidget.focusHighlightForeground': '#1a56c0',
      'editorSuggestWidgetStatus.foreground': '#445062',
      'editorHoverWidget.background': '#ffffff',
      'editorHoverWidget.foreground': '#1b2330',
      'editorHoverWidget.border': '#dbe0e6',
      'editorHoverWidget.statusBarBackground': '#ffffff',
      'editorMarkerNavigation.background': '#ffffff',
      'editorMarkerNavigationError.background': '#fbe8e7',
      'editorMarkerNavigationWarning.background': '#fbf0d9',
      'editorMarkerNavigationInfo.background': '#e3edfb',
      'editor.findMatchBorder': '#00000000',
      'quickInput.background': '#ffffff',
      'quickInput.foreground': '#1b2330',
      'quickInputTitle.background': '#ffffff',
      'quickInputList.focusBackground': '#1f5fd12e',
      'quickInputList.focusForeground': '#1b2330',
      'quickInputList.focusIconForeground': '#1b2330',
      'list.hoverBackground': '#1b23300e',
      'list.hoverForeground': '#1b2330',
      'list.activeSelectionBackground': '#1f5fd12e',
      'list.activeSelectionForeground': '#1b2330',
      'list.inactiveSelectionBackground': '#1b23301f',
      'list.inactiveSelectionForeground': '#1b2330',
      'list.focusBackground': '#1f5fd12e',
      'list.focusOutline': '#1f5fd1',
      'list.highlightForeground': '#1a56c0',
      'input.background': '#ffffff',
      'input.foreground': '#1b2330',
      'input.border': '#788393',
      'input.placeholderForeground': '#5a6677',
      'inputOption.activeBackground': '#e2ebfb',
      'inputOption.activeBorder': '#1f5fd1',
      'inputOption.activeForeground': '#1b2330',
      'inputValidation.errorBackground': '#fbe8e7',
      'inputValidation.errorBorder': '#b3261e',
      'inputValidation.warningBackground': '#fbf0d9',
      'inputValidation.warningBorder': '#8a5a00',
      'inputValidation.infoBackground': '#e3edfb',
      'inputValidation.infoBorder': '#1a5bb8',
      'dropdown.background': '#ffffff',
      'dropdown.foreground': '#1b2330',
      'dropdown.border': '#788393',
      'button.background': '#1f5fd1',
      'button.foreground': '#ffffff',
      'button.hoverBackground': '#184fb3',
      'badge.background': '#1f5fd1',
      'badge.foreground': '#ffffff',
      'scrollbar.shadow': '#00000000',
      'scrollbarSlider.background': '#1b233080',
      'scrollbarSlider.hoverBackground': '#1b23309e',
      'scrollbarSlider.activeBackground': '#1b2330c2',
      'minimap.background': '#f8f9fb',
      'minimap.selectionHighlight': '#1f5fd133',
      'minimap.findMatchHighlight': '#d6961457',
      'minimap.errorHighlight': '#b3261e',
      'minimap.warningHighlight': '#8a5a00',
      'minimapSlider.background': '#1b233012',
      'minimapSlider.hoverBackground': '#1b233019',
      'minimapSlider.activeBackground': '#1b233020',
      'minimapGutter.addedBackground': '#1f6a3a',
      'minimapGutter.modifiedBackground': '#775709',
      'minimapGutter.deletedBackground': '#a3373a',
      'editorOverviewRuler.border': '#00000000',
      'editorOverviewRuler.background': '#f8f9fb',
      'editorOverviewRuler.errorForeground': '#b3261e',
      'editorOverviewRuler.warningForeground': '#8a5a00',
      'editorOverviewRuler.infoForeground': '#1a5bb8',
      'editorOverviewRuler.addedForeground': '#1f6a3a',
      'editorOverviewRuler.modifiedForeground': '#775709',
      'editorOverviewRuler.deletedForeground': '#a3373a',
      'editorOverviewRuler.findMatchForeground': '#d6961457',
      'editorOverviewRuler.selectionHighlightForeground': '#1f5fd133',
      'editorOverviewRuler.bracketMatchForeground': '#1f5fd133',
      'peekView.border': '#1f5fd1',
      'peekViewEditor.background': '#f8f9fb',
      'peekViewEditor.matchHighlightBackground': '#d6961457',
      'peekViewEditorGutter.background': '#f8f9fb',
      'peekViewResult.background': '#f1f3f6',
      'peekViewResult.fileForeground': '#1b2330',
      'peekViewResult.lineForeground': '#445062',
      'peekViewResult.matchHighlightBackground': '#d6961457',
      'peekViewResult.selectionBackground': '#1f5fd12e',
      'peekViewResult.selectionForeground': '#1b2330',
      'peekViewTitle.background': '#f1f3f6',
      'peekViewTitleLabel.foreground': '#1b2330',
      'peekViewTitleDescription.foreground': '#445062',
      'menu.background': '#ffffff',
      'menu.foreground': '#1b2330',
      'menu.selectionBackground': '#1f5fd12e',
      'menu.selectionForeground': '#1b2330',
      'menu.separatorBackground': '#dbe0e6',
      'menu.border': '#dbe0e6',
    },
  },
  'inc-dark': {
    base: 'vs-dark',
    inherit: false,
    rules: [
      { token: '', foreground: 'e6eaf0' },
      { token: 'comment', foreground: '9aa7b6', fontStyle: 'italic' },
      { token: 'comment.doc', foreground: '9aa7b6', fontStyle: 'italic' },
      { token: 'keyword', foreground: 'a9a3f5' },
      { token: 'keyword.control', foreground: 'a9a3f5' },
      { token: 'keyword.operator', foreground: 'aab4c1' },
      { token: 'storage', foreground: 'a9a3f5' },
      { token: 'storage.type', foreground: 'a9a3f5' },
      { token: 'string', foreground: 'a6cb86' },
      { token: 'string.escape', foreground: 'ee9a8a' },
      { token: 'string.invalid', foreground: 'f28083' },
      { token: 'number', foreground: 'e0a46c' },
      { token: 'number.hex', foreground: 'e0a46c' },
      { token: 'number.float', foreground: 'e0a46c' },
      { token: 'number.octal', foreground: 'e0a46c' },
      { token: 'number.binary', foreground: 'e0a46c' },
      { token: 'regexp', foreground: 'ee9a8a' },
      { token: 'regexp.escape', foreground: 'e0a46c' },
      { token: 'regexp.escape.control', foreground: 'a9a3f5' },
      { token: 'type', foreground: 'e6a0c4' },
      { token: 'type.identifier', foreground: 'e6a0c4' },
      { token: 'entity.name.type', foreground: 'e6a0c4' },
      { token: 'entity.name.class', foreground: 'e6a0c4' },
      { token: 'entity.name.function', foreground: '5cc8c8' },
      { token: 'function', foreground: '5cc8c8' },
      { token: 'support.function', foreground: '5cc8c8' },
      { token: 'identifier', foreground: 'd5dbe3' },
      { token: 'variable', foreground: 'd5dbe3' },
      { token: 'variable.predefined', foreground: 'ee9a8a' },
      { token: 'variable.parameter', foreground: 'd5dbe3' },
      { token: 'constant', foreground: 'ee9a8a' },
      { token: 'constant.language', foreground: 'ee9a8a' },
      { token: 'predefined', foreground: 'ee9a8a' },
      { token: 'operator', foreground: 'aab4c1' },
      { token: 'delimiter', foreground: 'a0abb9' },
      { token: 'delimiter.bracket', foreground: 'a0abb9' },
      { token: 'delimiter.parenthesis', foreground: 'a0abb9' },
      { token: 'delimiter.square', foreground: 'a0abb9' },
      { token: 'delimiter.curly', foreground: 'a0abb9' },
      { token: 'delimiter.angle', foreground: 'a0abb9' },
      { token: 'tag', foreground: '79b0f2' },
      { token: 'metatag', foreground: '79b0f2' },
      { token: 'attribute.name', foreground: 'd8b878' },
      { token: 'attribute.value', foreground: 'a6cb86' },
      { token: 'annotation', foreground: 'd8b878' },
      { token: 'invalid', foreground: 'f28083', fontStyle: 'underline' },
      { token: 'string.key.json', foreground: 'd8b878' },
      { token: 'string.value.json', foreground: 'a6cb86' },
      { token: 'number.json', foreground: 'e0a46c' },
      { token: 'keyword.json', foreground: 'ee9a8a' },
      { token: 'delimiter.bracket.json', foreground: 'a0abb9' },
      { token: 'delimiter.array.json', foreground: 'a0abb9' },
      { token: 'delimiter.colon.json', foreground: 'a0abb9' },
      { token: 'delimiter.comma.json', foreground: 'a0abb9' },
      { token: 'tag.css', foreground: '79b0f2' },
      { token: 'tag.id.css', foreground: 'e6a0c4' },
      { token: 'tag.class.css', foreground: 'e6a0c4' },
      { token: 'attribute.name.css', foreground: 'd8b878' },
      { token: 'attribute.value.css', foreground: 'a6cb86' },
      { token: 'attribute.value.number.css', foreground: 'e0a46c' },
      { token: 'attribute.value.unit.css', foreground: 'e0a46c' },
      { token: 'attribute.value.hex.css', foreground: 'e0a46c' },
      { token: 'keyword.css', foreground: 'a9a3f5' },
      { token: 'string.css', foreground: 'a6cb86' },
      { token: 'delimiter.css', foreground: 'a0abb9' },
      { token: 'variable.scss', foreground: 'd5dbe3' },
      { token: 'tag.html', foreground: '79b0f2' },
      { token: 'delimiter.html', foreground: 'a0abb9' },
      { token: 'attribute.name.html', foreground: 'd8b878' },
      { token: 'attribute.value.html', foreground: 'a6cb86' },
      { token: 'metatag.html', foreground: '79b0f2' },
      { token: 'metatag.content.html', foreground: 'a6cb86' },
      { token: 'comment.html', foreground: '9aa7b6', fontStyle: 'italic' },
      { token: 'keyword.md', foreground: 'a9a3f5', fontStyle: 'bold' },
      { token: 'markup.heading', foreground: 'a9a3f5', fontStyle: 'bold' },
      { token: 'markup.heading.md', foreground: 'a9a3f5', fontStyle: 'bold' },
      { token: 'string.md', foreground: 'd5dbe3' },
      { token: 'strong', foreground: 'e6eaf0', fontStyle: 'bold' },
      { token: 'emphasis', foreground: 'e6eaf0', fontStyle: 'italic' },
      { token: 'markup.bold', foreground: 'e6eaf0', fontStyle: 'bold' },
      { token: 'markup.italic', foreground: 'e6eaf0', fontStyle: 'italic' },
      { token: 'markup.inline.raw', foreground: 'a6cb86' },
      { token: 'string.link.md', foreground: '93b4ee', fontStyle: 'underline' },
      { token: 'variable.source.md', foreground: 'a6cb86' },
      { token: 'variable.md', foreground: 'a6cb86' },
      { token: 'meta.separator', foreground: 'a0abb9' },
      { token: 'meta.tag', foreground: '79b0f2' },
      { token: 'predefined.sql', foreground: '5cc8c8' },
      { token: 'operator.sql', foreground: 'aab4c1' },
      { token: 'key', foreground: 'd8b878' },
      { token: 'keyword.yaml', foreground: 'ee9a8a' },
    ],
    colors: {
      focusBorder: '#7ba5ee',
      foreground: '#e6eaf0',
      descriptionForeground: '#aab4c1',
      errorForeground: '#f28083',
      'widget.shadow': '#00000000',
      'textLink.foreground': '#93b4ee',
      'textLink.activeForeground': '#93b4ee',
      'textCodeBlock.background': '#232a32',
      'editor.background': '#1b2026',
      'editor.foreground': '#e6eaf0',
      'editor.lineHighlightBackground': '#ffffff0a',
      'editor.lineHighlightBorder': '#00000000',
      'editor.selectionBackground': '#507dcd45',
      'editor.inactiveSelectionBackground': '#ffffff1a',
      'editor.selectionHighlightBackground': '#507dcd23',
      'editor.wordHighlightBackground': '#ffffff1a',
      'editor.wordHighlightStrongBackground': '#507dcd45',
      'editor.findMatchBackground': '#e0b0545c',
      'editor.findMatchHighlightBackground': '#e0b05433',
      'editor.findRangeHighlightBackground': '#ffffff0a',
      'editor.hoverHighlightBackground': '#ffffff0d',
      'editor.rangeHighlightBackground': '#ffffff0a',
      'editor.symbolHighlightBackground': '#507dcd5c',
      'editor.foldBackground': '#ffffff0a',
      'editorBracketMatch.background': '#507dcd5c',
      'editorBracketMatch.border': '#00000000',
      'editorCursor.foreground': '#e6eaf0',
      'editorCursor.background': '#1b2026',
      'editorLineNumber.foreground': '#7f8b9b',
      'editorLineNumber.activeForeground': '#d0d6de',
      'editorIndentGuide.background': '#ffffff1f',
      'editorIndentGuide.activeBackground': '#ffffff38',
      'editorIndentGuide.background1': '#ffffff1f',
      'editorIndentGuide.activeBackground1': '#ffffff38',
      'editorWhitespace.foreground': '#ffffff1f',
      'editorRuler.foreground': '#ffffff1f',
      'editorLink.activeForeground': '#93b4ee',
      'editorCodeLens.foreground': '#8b96a5',
      'editorInlayHint.foreground': '#8b96a5',
      'editorInlayHint.background': '#ffffff0d',
      'editorGhostText.foreground': '#8b96a5',
      'editorUnnecessaryCode.opacity': '#000000a0',
      'editorStickyScroll.background': '#1b2026',
      'editorStickyScrollHover.background': '#ffffff0d',
      'editorGutter.background': '#1b2026',
      'editorGutter.addedBackground': '#86bd7a',
      'editorGutter.modifiedBackground': '#cbaa6a',
      'editorGutter.deletedBackground': '#dc9293',
      'editorGutter.foldingControlForeground': '#aab4c1',
      'editorError.foreground': '#f28083',
      'editorWarning.foreground': '#e0b45a',
      'editorInfo.foreground': '#7db4f2',
      'editorHint.foreground': '#8b96a5',
      'editorError.border': '#00000000',
      'editorWarning.border': '#00000000',
      'editorInfo.border': '#00000000',
      'diffEditor.insertedTextBackground': '#86bd7a24',
      'diffEditor.removedTextBackground': '#d4858624',
      'diffEditor.insertedLineBackground': '#86bd7a12',
      'diffEditor.removedLineBackground': '#d4858612',
      'diffEditor.border': '#272e36',
      'diffEditor.diagonalFill': '#ffffff1f',
      'diffEditorGutter.insertedLineBackground': '#86bd7a24',
      'diffEditorGutter.removedLineBackground': '#d4858624',
      'editorWidget.background': '#232a32',
      'editorWidget.foreground': '#e6eaf0',
      'editorWidget.border': '#272e36',
      'editorWidget.resizeBorder': '#7ba5ee',
      'editorSuggestWidget.background': '#232a32',
      'editorSuggestWidget.foreground': '#e6eaf0',
      'editorSuggestWidget.border': '#272e36',
      'editorSuggestWidget.selectedBackground': '#507dcd4d',
      'editorSuggestWidget.selectedForeground': '#e6eaf0',
      'editorSuggestWidget.highlightForeground': '#93b4ee',
      'editorSuggestWidget.focusHighlightForeground': '#93b4ee',
      'editorSuggestWidgetStatus.foreground': '#aab4c1',
      'editorHoverWidget.background': '#232a32',
      'editorHoverWidget.foreground': '#e6eaf0',
      'editorHoverWidget.border': '#272e36',
      'editorHoverWidget.statusBarBackground': '#232a32',
      'editorMarkerNavigation.background': '#232a32',
      'editorMarkerNavigationError.background': '#3b2226',
      'editorMarkerNavigationWarning.background': '#392f1c',
      'editorMarkerNavigationInfo.background': '#1b2d45',
      'editor.findMatchBorder': '#00000000',
      'quickInput.background': '#232a32',
      'quickInput.foreground': '#e6eaf0',
      'quickInputTitle.background': '#232a32',
      'quickInputList.focusBackground': '#507dcd4d',
      'quickInputList.focusForeground': '#e6eaf0',
      'quickInputList.focusIconForeground': '#e6eaf0',
      'list.hoverBackground': '#ffffff0d',
      'list.hoverForeground': '#e6eaf0',
      'list.activeSelectionBackground': '#507dcd4d',
      'list.activeSelectionForeground': '#e6eaf0',
      'list.inactiveSelectionBackground': '#94a3b833',
      'list.inactiveSelectionForeground': '#e6eaf0',
      'list.focusBackground': '#507dcd4d',
      'list.focusOutline': '#7ba5ee',
      'list.highlightForeground': '#93b4ee',
      'input.background': '#1f252c',
      'input.foreground': '#e6eaf0',
      'input.border': '#6b7583',
      'input.placeholderForeground': '#8b96a5',
      'inputOption.activeBackground': '#1c2c47',
      'inputOption.activeBorder': '#7ba5ee',
      'inputOption.activeForeground': '#e6eaf0',
      'inputValidation.errorBackground': '#3b2226',
      'inputValidation.errorBorder': '#f28083',
      'inputValidation.warningBackground': '#392f1c',
      'inputValidation.warningBorder': '#e0b45a',
      'inputValidation.infoBackground': '#1b2d45',
      'inputValidation.infoBorder': '#7db4f2',
      'dropdown.background': '#1f252c',
      'dropdown.foreground': '#e6eaf0',
      'dropdown.border': '#6b7583',
      'button.background': '#4170cd',
      'button.foreground': '#ffffff',
      'button.hoverBackground': '#3563b8',
      'badge.background': '#4170cd',
      'badge.foreground': '#ffffff',
      'scrollbar.shadow': '#00000000',
      'scrollbarSlider.background': '#ffffff5c',
      'scrollbarSlider.hoverBackground': '#ffffff80',
      'scrollbarSlider.activeBackground': '#ffffffa8',
      'minimap.background': '#1b2026',
      'minimap.selectionHighlight': '#507dcd45',
      'minimap.findMatchHighlight': '#e0b0545c',
      'minimap.errorHighlight': '#f28083',
      'minimap.warningHighlight': '#e0b45a',
      'minimapSlider.background': '#ffffff12',
      'minimapSlider.hoverBackground': '#ffffff19',
      'minimapSlider.activeBackground': '#ffffff20',
      'minimapGutter.addedBackground': '#86bd7a',
      'minimapGutter.modifiedBackground': '#cbaa6a',
      'minimapGutter.deletedBackground': '#dc9293',
      'editorOverviewRuler.border': '#00000000',
      'editorOverviewRuler.background': '#1b2026',
      'editorOverviewRuler.errorForeground': '#f28083',
      'editorOverviewRuler.warningForeground': '#e0b45a',
      'editorOverviewRuler.infoForeground': '#7db4f2',
      'editorOverviewRuler.addedForeground': '#86bd7a',
      'editorOverviewRuler.modifiedForeground': '#cbaa6a',
      'editorOverviewRuler.deletedForeground': '#dc9293',
      'editorOverviewRuler.findMatchForeground': '#e0b0545c',
      'editorOverviewRuler.selectionHighlightForeground': '#507dcd45',
      'editorOverviewRuler.bracketMatchForeground': '#507dcd5c',
      'peekView.border': '#7ba5ee',
      'peekViewEditor.background': '#1b2026',
      'peekViewEditor.matchHighlightBackground': '#e0b0545c',
      'peekViewEditorGutter.background': '#1b2026',
      'peekViewResult.background': '#171b20',
      'peekViewResult.fileForeground': '#e6eaf0',
      'peekViewResult.lineForeground': '#aab4c1',
      'peekViewResult.matchHighlightBackground': '#e0b0545c',
      'peekViewResult.selectionBackground': '#507dcd4d',
      'peekViewResult.selectionForeground': '#e6eaf0',
      'peekViewTitle.background': '#171b20',
      'peekViewTitleLabel.foreground': '#e6eaf0',
      'peekViewTitleDescription.foreground': '#aab4c1',
      'menu.background': '#232a32',
      'menu.foreground': '#e6eaf0',
      'menu.selectionBackground': '#507dcd4d',
      'menu.selectionForeground': '#e6eaf0',
      'menu.separatorBackground': '#272e36',
      'menu.border': '#272e36',
    },
  },
  'inc-hc-light': {
    base: 'hc-light',
    inherit: false,
    rules: [
      { token: '', foreground: '000000' },
      { token: 'comment', foreground: '46505e', fontStyle: 'italic' },
      { token: 'comment.doc', foreground: '46505e', fontStyle: 'italic' },
      { token: 'keyword', foreground: '3c2ea6' },
      { token: 'keyword.control', foreground: '3c2ea6' },
      { token: 'keyword.operator', foreground: '2a323e' },
      { token: 'storage', foreground: '3c2ea6' },
      { token: 'storage.type', foreground: '3c2ea6' },
      { token: 'string', foreground: '2f5a0e' },
      { token: 'string.escape', foreground: '8a2e0d' },
      { token: 'string.invalid', foreground: '9e0d0d' },
      { token: 'number', foreground: '7a3a00' },
      { token: 'number.hex', foreground: '7a3a00' },
      { token: 'number.float', foreground: '7a3a00' },
      { token: 'number.octal', foreground: '7a3a00' },
      { token: 'number.binary', foreground: '7a3a00' },
      { token: 'regexp', foreground: '8a2e0d' },
      { token: 'regexp.escape', foreground: '7a3a00' },
      { token: 'regexp.escape.control', foreground: '3c2ea6' },
      { token: 'type', foreground: '8a2a66' },
      { token: 'type.identifier', foreground: '8a2a66' },
      { token: 'entity.name.type', foreground: '8a2a66' },
      { token: 'entity.name.class', foreground: '8a2a66' },
      { token: 'entity.name.function', foreground: '00545c' },
      { token: 'function', foreground: '00545c' },
      { token: 'support.function', foreground: '00545c' },
      { token: 'identifier', foreground: '0b0f16' },
      { token: 'variable', foreground: '0b0f16' },
      { token: 'variable.predefined', foreground: '8a2e0d' },
      { token: 'variable.parameter', foreground: '0b0f16' },
      { token: 'constant', foreground: '8a2e0d' },
      { token: 'constant.language', foreground: '8a2e0d' },
      { token: 'predefined', foreground: '8a2e0d' },
      { token: 'operator', foreground: '2a323e' },
      { token: 'delimiter', foreground: '3a424e' },
      { token: 'delimiter.bracket', foreground: '3a424e' },
      { token: 'delimiter.parenthesis', foreground: '3a424e' },
      { token: 'delimiter.square', foreground: '3a424e' },
      { token: 'delimiter.curly', foreground: '3a424e' },
      { token: 'delimiter.angle', foreground: '3a424e' },
      { token: 'tag', foreground: '0a3694' },
      { token: 'metatag', foreground: '0a3694' },
      { token: 'attribute.name', foreground: '6b4400' },
      { token: 'attribute.value', foreground: '2f5a0e' },
      { token: 'annotation', foreground: '6b4400' },
      { token: 'invalid', foreground: '9e0d0d', fontStyle: 'underline' },
      { token: 'string.key.json', foreground: '6b4400' },
      { token: 'string.value.json', foreground: '2f5a0e' },
      { token: 'number.json', foreground: '7a3a00' },
      { token: 'keyword.json', foreground: '8a2e0d' },
      { token: 'delimiter.bracket.json', foreground: '3a424e' },
      { token: 'delimiter.array.json', foreground: '3a424e' },
      { token: 'delimiter.colon.json', foreground: '3a424e' },
      { token: 'delimiter.comma.json', foreground: '3a424e' },
      { token: 'tag.css', foreground: '0a3694' },
      { token: 'tag.id.css', foreground: '8a2a66' },
      { token: 'tag.class.css', foreground: '8a2a66' },
      { token: 'attribute.name.css', foreground: '6b4400' },
      { token: 'attribute.value.css', foreground: '2f5a0e' },
      { token: 'attribute.value.number.css', foreground: '7a3a00' },
      { token: 'attribute.value.unit.css', foreground: '7a3a00' },
      { token: 'attribute.value.hex.css', foreground: '7a3a00' },
      { token: 'keyword.css', foreground: '3c2ea6' },
      { token: 'string.css', foreground: '2f5a0e' },
      { token: 'delimiter.css', foreground: '3a424e' },
      { token: 'variable.scss', foreground: '0b0f16' },
      { token: 'tag.html', foreground: '0a3694' },
      { token: 'delimiter.html', foreground: '3a424e' },
      { token: 'attribute.name.html', foreground: '6b4400' },
      { token: 'attribute.value.html', foreground: '2f5a0e' },
      { token: 'metatag.html', foreground: '0a3694' },
      { token: 'metatag.content.html', foreground: '2f5a0e' },
      { token: 'comment.html', foreground: '46505e', fontStyle: 'italic' },
      { token: 'keyword.md', foreground: '3c2ea6', fontStyle: 'bold' },
      { token: 'markup.heading', foreground: '3c2ea6', fontStyle: 'bold' },
      { token: 'markup.heading.md', foreground: '3c2ea6', fontStyle: 'bold' },
      { token: 'string.md', foreground: '0b0f16' },
      { token: 'strong', foreground: '000000', fontStyle: 'bold' },
      { token: 'emphasis', foreground: '000000', fontStyle: 'italic' },
      { token: 'markup.bold', foreground: '000000', fontStyle: 'bold' },
      { token: 'markup.italic', foreground: '000000', fontStyle: 'italic' },
      { token: 'markup.inline.raw', foreground: '2f5a0e' },
      { token: 'string.link.md', foreground: '0a3690', fontStyle: 'underline' },
      { token: 'variable.source.md', foreground: '2f5a0e' },
      { token: 'variable.md', foreground: '2f5a0e' },
      { token: 'meta.separator', foreground: '3a424e' },
      { token: 'meta.tag', foreground: '0a3694' },
      { token: 'predefined.sql', foreground: '00545c' },
      { token: 'operator.sql', foreground: '2a323e' },
      { token: 'key', foreground: '6b4400' },
      { token: 'keyword.yaml', foreground: '8a2e0d' },
    ],
    colors: {
      focusBorder: '#0b3fa8',
      foreground: '#000000',
      descriptionForeground: '#1a1f27',
      errorForeground: '#9e0d0d',
      'widget.shadow': '#00000000',
      'textLink.foreground': '#0a3690',
      'textLink.activeForeground': '#0a3690',
      'textCodeBlock.background': '#ffffff',
      'editor.background': '#ffffff',
      'editor.foreground': '#000000',
      'editor.lineHighlightBackground': '#0000000f',
      'editor.lineHighlightBorder': '#00000000',
      'editor.selectionBackground': '#0b3fa83d',
      'editor.inactiveSelectionBackground': '#00000024',
      'editor.selectionHighlightBackground': '#0b3fa81f',
      'editor.wordHighlightBackground': '#00000024',
      'editor.wordHighlightStrongBackground': '#0b3fa83d',
      'editor.findMatchBackground': '#ffbe0073',
      'editor.findMatchHighlightBackground': '#ffbe003f',
      'editor.findRangeHighlightBackground': '#0000000f',
      'editor.hoverHighlightBackground': '#0000000f',
      'editor.rangeHighlightBackground': '#0000000f',
      'editor.symbolHighlightBackground': '#0b3fa83d',
      'editor.foldBackground': '#0000000f',
      'editorBracketMatch.background': '#0b3fa83d',
      'editorBracketMatch.border': '#000000',
      'editorCursor.foreground': '#000000',
      'editorCursor.background': '#ffffff',
      'editorLineNumber.foreground': '#3a424e',
      'editorLineNumber.activeForeground': '#000000',
      'editorIndentGuide.background': '#00000040',
      'editorIndentGuide.activeBackground': '#00000099',
      'editorIndentGuide.background1': '#00000040',
      'editorIndentGuide.activeBackground1': '#00000099',
      'editorWhitespace.foreground': '#00000040',
      'editorRuler.foreground': '#00000040',
      'editorLink.activeForeground': '#0a3690',
      'editorCodeLens.foreground': '#3a424e',
      'editorInlayHint.foreground': '#3a424e',
      'editorInlayHint.background': '#0000000f',
      'editorGhostText.foreground': '#3a424e',
      'editorUnnecessaryCode.opacity': '#000000a0',
      'editorStickyScroll.background': '#ffffff',
      'editorStickyScrollHover.background': '#0000000f',
      'editorGutter.background': '#ffffff',
      'editorGutter.addedBackground': '#13562e',
      'editorGutter.modifiedBackground': '#634600',
      'editorGutter.deletedBackground': '#911d20',
      'editorGutter.foldingControlForeground': '#1a1f27',
      'editorError.foreground': '#9e0d0d',
      'editorWarning.foreground': '#6b4400',
      'editorInfo.foreground': '#0a3f9e',
      'editorHint.foreground': '#3a424e',
      'editorError.border': '#00000000',
      'editorWarning.border': '#00000000',
      'editorInfo.border': '#00000000',
      'diffEditor.insertedTextBackground': '#14592f29',
      'diffEditor.removedTextBackground': '#9c1f2229',
      'diffEditor.insertedLineBackground': '#14592f15',
      'diffEditor.removedLineBackground': '#9c1f2215',
      'diffEditor.border': '#6b7380',
      'diffEditor.diagonalFill': '#00000040',
      'diffEditorGutter.insertedLineBackground': '#14592f29',
      'diffEditorGutter.removedLineBackground': '#9c1f2229',
      'editorWidget.background': '#ffffff',
      'editorWidget.foreground': '#000000',
      'editorWidget.border': '#000000',
      'editorWidget.resizeBorder': '#0b3fa8',
      'editorSuggestWidget.background': '#ffffff',
      'editorSuggestWidget.foreground': '#000000',
      'editorSuggestWidget.border': '#000000',
      'editorSuggestWidget.selectedBackground': '#0b3fa82e',
      'editorSuggestWidget.selectedForeground': '#000000',
      'editorSuggestWidget.highlightForeground': '#0a3690',
      'editorSuggestWidget.focusHighlightForeground': '#0a3690',
      'editorSuggestWidgetStatus.foreground': '#1a1f27',
      'editorHoverWidget.background': '#ffffff',
      'editorHoverWidget.foreground': '#000000',
      'editorHoverWidget.border': '#000000',
      'editorHoverWidget.statusBarBackground': '#ffffff',
      'editorMarkerNavigation.background': '#ffffff',
      'editorMarkerNavigationError.background': '#fde8e8',
      'editorMarkerNavigationWarning.background': '#fdf1d6',
      'editorMarkerNavigationInfo.background': '#e1ecfc',
      'editor.findMatchBorder': '#000000',
      'quickInput.background': '#ffffff',
      'quickInput.foreground': '#000000',
      'quickInputTitle.background': '#ffffff',
      'quickInputList.focusBackground': '#0b3fa82e',
      'quickInputList.focusForeground': '#000000',
      'quickInputList.focusIconForeground': '#000000',
      'list.hoverBackground': '#0000000f',
      'list.hoverForeground': '#000000',
      'list.activeSelectionBackground': '#0b3fa82e',
      'list.activeSelectionForeground': '#000000',
      'list.inactiveSelectionBackground': '#00000017',
      'list.inactiveSelectionForeground': '#000000',
      'list.focusBackground': '#0b3fa82e',
      'list.focusOutline': '#0b3fa8',
      'list.highlightForeground': '#0a3690',
      'input.background': '#ffffff',
      'input.foreground': '#000000',
      'input.border': '#3d4652',
      'input.placeholderForeground': '#3a424e',
      'inputOption.activeBackground': '#dbe6fb',
      'inputOption.activeBorder': '#0b3fa8',
      'inputOption.activeForeground': '#000000',
      'inputValidation.errorBackground': '#fde8e8',
      'inputValidation.errorBorder': '#9e0d0d',
      'inputValidation.warningBackground': '#fdf1d6',
      'inputValidation.warningBorder': '#6b4400',
      'inputValidation.infoBackground': '#e1ecfc',
      'inputValidation.infoBorder': '#0a3f9e',
      'dropdown.background': '#ffffff',
      'dropdown.foreground': '#000000',
      'dropdown.border': '#3d4652',
      'button.background': '#0b3fa8',
      'button.foreground': '#ffffff',
      'button.hoverBackground': '#082f80',
      'badge.background': '#0b3fa8',
      'badge.foreground': '#ffffff',
      'scrollbar.shadow': '#00000000',
      'scrollbarSlider.background': '#0000009e',
      'scrollbarSlider.hoverBackground': '#000000c7',
      'scrollbarSlider.activeBackground': '#000000eb',
      'minimap.background': '#ffffff',
      'minimap.selectionHighlight': '#0b3fa83d',
      'minimap.findMatchHighlight': '#ffbe0073',
      'minimap.errorHighlight': '#9e0d0d',
      'minimap.warningHighlight': '#6b4400',
      'minimapSlider.background': '#00000024',
      'minimapSlider.hoverBackground': '#00000032',
      'minimapSlider.activeBackground': '#00000041',
      'minimapGutter.addedBackground': '#13562e',
      'minimapGutter.modifiedBackground': '#634600',
      'minimapGutter.deletedBackground': '#911d20',
      'editorOverviewRuler.border': '#00000000',
      'editorOverviewRuler.background': '#ffffff',
      'editorOverviewRuler.errorForeground': '#9e0d0d',
      'editorOverviewRuler.warningForeground': '#6b4400',
      'editorOverviewRuler.infoForeground': '#0a3f9e',
      'editorOverviewRuler.addedForeground': '#13562e',
      'editorOverviewRuler.modifiedForeground': '#634600',
      'editorOverviewRuler.deletedForeground': '#911d20',
      'editorOverviewRuler.findMatchForeground': '#ffbe0073',
      'editorOverviewRuler.selectionHighlightForeground': '#0b3fa83d',
      'editorOverviewRuler.bracketMatchForeground': '#0b3fa83d',
      'peekView.border': '#0b3fa8',
      'peekViewEditor.background': '#ffffff',
      'peekViewEditor.matchHighlightBackground': '#ffbe0073',
      'peekViewEditorGutter.background': '#ffffff',
      'peekViewResult.background': '#ffffff',
      'peekViewResult.fileForeground': '#000000',
      'peekViewResult.lineForeground': '#1a1f27',
      'peekViewResult.matchHighlightBackground': '#ffbe0073',
      'peekViewResult.selectionBackground': '#0b3fa82e',
      'peekViewResult.selectionForeground': '#000000',
      'peekViewTitle.background': '#ffffff',
      'peekViewTitleLabel.foreground': '#000000',
      'peekViewTitleDescription.foreground': '#1a1f27',
      'menu.background': '#ffffff',
      'menu.foreground': '#000000',
      'menu.selectionBackground': '#0b3fa82e',
      'menu.selectionForeground': '#000000',
      'menu.separatorBackground': '#6b7380',
      'menu.border': '#000000',
      contrastBorder: '#000000',
      contrastActiveBorder: '#0b3fa8',
      'list.activeSelectionBorder': '#000000',
      'list.inactiveSelectionBorder': '#000000',
      'list.hoverBorder': '#3d4652',
      'minimapSlider.border': '#3d4652',
    },
  },
  'inc-hc-dark': {
    base: 'hc-black',
    inherit: false,
    rules: [
      { token: '', foreground: 'ffffff' },
      { token: 'comment', foreground: 'b4bdc9', fontStyle: 'italic' },
      { token: 'comment.doc', foreground: 'b4bdc9', fontStyle: 'italic' },
      { token: 'keyword', foreground: 'c2bdff' },
      { token: 'keyword.control', foreground: 'c2bdff' },
      { token: 'keyword.operator', foreground: 'd0d6de' },
      { token: 'storage', foreground: 'c2bdff' },
      { token: 'storage.type', foreground: 'c2bdff' },
      { token: 'string', foreground: 'bddc9f' },
      { token: 'string.escape', foreground: 'f5b89c' },
      { token: 'string.invalid', foreground: 'ff9a9e' },
      { token: 'number', foreground: 'f0c090' },
      { token: 'number.hex', foreground: 'f0c090' },
      { token: 'number.float', foreground: 'f0c090' },
      { token: 'number.octal', foreground: 'f0c090' },
      { token: 'number.binary', foreground: 'f0c090' },
      { token: 'regexp', foreground: 'f5b89c' },
      { token: 'regexp.escape', foreground: 'f0c090' },
      { token: 'regexp.escape.control', foreground: 'c2bdff' },
      { token: 'type', foreground: 'f2b6d3' },
      { token: 'type.identifier', foreground: 'f2b6d3' },
      { token: 'entity.name.type', foreground: 'f2b6d3' },
      { token: 'entity.name.class', foreground: 'f2b6d3' },
      { token: 'entity.name.function', foreground: '86dede' },
      { token: 'function', foreground: '86dede' },
      { token: 'support.function', foreground: '86dede' },
      { token: 'identifier', foreground: 'f0f3f7' },
      { token: 'variable', foreground: 'f0f3f7' },
      { token: 'variable.predefined', foreground: 'f5b89c' },
      { token: 'variable.parameter', foreground: 'f0f3f7' },
      { token: 'constant', foreground: 'f5b89c' },
      { token: 'constant.language', foreground: 'f5b89c' },
      { token: 'predefined', foreground: 'f5b89c' },
      { token: 'operator', foreground: 'd0d6de' },
      { token: 'delimiter', foreground: 'c5ccd6' },
      { token: 'delimiter.bracket', foreground: 'c5ccd6' },
      { token: 'delimiter.parenthesis', foreground: 'c5ccd6' },
      { token: 'delimiter.square', foreground: 'c5ccd6' },
      { token: 'delimiter.curly', foreground: 'c5ccd6' },
      { token: 'delimiter.angle', foreground: 'c5ccd6' },
      { token: 'tag', foreground: '8ab8ff' },
      { token: 'metatag', foreground: '8ab8ff' },
      { token: 'attribute.name', foreground: 'ecd08c' },
      { token: 'attribute.value', foreground: 'bddc9f' },
      { token: 'annotation', foreground: 'ecd08c' },
      { token: 'invalid', foreground: 'ff9a9e', fontStyle: 'underline' },
      { token: 'string.key.json', foreground: 'ecd08c' },
      { token: 'string.value.json', foreground: 'bddc9f' },
      { token: 'number.json', foreground: 'f0c090' },
      { token: 'keyword.json', foreground: 'f5b89c' },
      { token: 'delimiter.bracket.json', foreground: 'c5ccd6' },
      { token: 'delimiter.array.json', foreground: 'c5ccd6' },
      { token: 'delimiter.colon.json', foreground: 'c5ccd6' },
      { token: 'delimiter.comma.json', foreground: 'c5ccd6' },
      { token: 'tag.css', foreground: '8ab8ff' },
      { token: 'tag.id.css', foreground: 'f2b6d3' },
      { token: 'tag.class.css', foreground: 'f2b6d3' },
      { token: 'attribute.name.css', foreground: 'ecd08c' },
      { token: 'attribute.value.css', foreground: 'bddc9f' },
      { token: 'attribute.value.number.css', foreground: 'f0c090' },
      { token: 'attribute.value.unit.css', foreground: 'f0c090' },
      { token: 'attribute.value.hex.css', foreground: 'f0c090' },
      { token: 'keyword.css', foreground: 'c2bdff' },
      { token: 'string.css', foreground: 'bddc9f' },
      { token: 'delimiter.css', foreground: 'c5ccd6' },
      { token: 'variable.scss', foreground: 'f0f3f7' },
      { token: 'tag.html', foreground: '8ab8ff' },
      { token: 'delimiter.html', foreground: 'c5ccd6' },
      { token: 'attribute.name.html', foreground: 'ecd08c' },
      { token: 'attribute.value.html', foreground: 'bddc9f' },
      { token: 'metatag.html', foreground: '8ab8ff' },
      { token: 'metatag.content.html', foreground: 'bddc9f' },
      { token: 'comment.html', foreground: 'b4bdc9', fontStyle: 'italic' },
      { token: 'keyword.md', foreground: 'c2bdff', fontStyle: 'bold' },
      { token: 'markup.heading', foreground: 'c2bdff', fontStyle: 'bold' },
      { token: 'markup.heading.md', foreground: 'c2bdff', fontStyle: 'bold' },
      { token: 'string.md', foreground: 'f0f3f7' },
      { token: 'strong', foreground: 'ffffff', fontStyle: 'bold' },
      { token: 'emphasis', foreground: 'ffffff', fontStyle: 'italic' },
      { token: 'markup.bold', foreground: 'ffffff', fontStyle: 'bold' },
      { token: 'markup.italic', foreground: 'ffffff', fontStyle: 'italic' },
      { token: 'markup.inline.raw', foreground: 'bddc9f' },
      { token: 'string.link.md', foreground: 'a3c7ff', fontStyle: 'underline' },
      { token: 'variable.source.md', foreground: 'bddc9f' },
      { token: 'variable.md', foreground: 'bddc9f' },
      { token: 'meta.separator', foreground: 'c5ccd6' },
      { token: 'meta.tag', foreground: '8ab8ff' },
      { token: 'predefined.sql', foreground: '86dede' },
      { token: 'operator.sql', foreground: 'd0d6de' },
      { token: 'key', foreground: 'ecd08c' },
      { token: 'keyword.yaml', foreground: 'f5b89c' },
    ],
    colors: {
      focusBorder: '#8ab8ff',
      foreground: '#ffffff',
      descriptionForeground: '#e4e8ee',
      errorForeground: '#ff9a9e',
      'widget.shadow': '#00000000',
      'textLink.foreground': '#a3c7ff',
      'textLink.activeForeground': '#a3c7ff',
      'textCodeBlock.background': '#000000',
      'editor.background': '#000000',
      'editor.foreground': '#ffffff',
      'editor.lineHighlightBackground': '#ffffff14',
      'editor.lineHighlightBorder': '#00000000',
      'editor.selectionBackground': '#6fa8ff52',
      'editor.inactiveSelectionBackground': '#ffffff38',
      'editor.selectionHighlightBackground': '#6fa8ff29',
      'editor.wordHighlightBackground': '#ffffff38',
      'editor.wordHighlightStrongBackground': '#6fa8ff52',
      'editor.findMatchBackground': '#ffd54a66',
      'editor.findMatchHighlightBackground': '#ffd54a38',
      'editor.findRangeHighlightBackground': '#ffffff14',
      'editor.hoverHighlightBackground': '#ffffff24',
      'editor.rangeHighlightBackground': '#ffffff14',
      'editor.symbolHighlightBackground': '#6fa8ff66',
      'editor.foldBackground': '#ffffff14',
      'editorBracketMatch.background': '#6fa8ff66',
      'editorBracketMatch.border': '#ffffff',
      'editorCursor.foreground': '#ffffff',
      'editorCursor.background': '#000000',
      'editorLineNumber.foreground': '#c5ccd6',
      'editorLineNumber.activeForeground': '#ffffff',
      'editorIndentGuide.background': '#ffffff40',
      'editorIndentGuide.activeBackground': '#ffffff99',
      'editorIndentGuide.background1': '#ffffff40',
      'editorIndentGuide.activeBackground1': '#ffffff99',
      'editorWhitespace.foreground': '#ffffff40',
      'editorRuler.foreground': '#ffffff40',
      'editorLink.activeForeground': '#a3c7ff',
      'editorCodeLens.foreground': '#c5ccd6',
      'editorInlayHint.foreground': '#c5ccd6',
      'editorInlayHint.background': '#ffffff24',
      'editorGhostText.foreground': '#c5ccd6',
      'editorUnnecessaryCode.opacity': '#000000a0',
      'editorStickyScroll.background': '#000000',
      'editorStickyScrollHover.background': '#ffffff24',
      'editorGutter.background': '#000000',
      'editorGutter.addedBackground': '#8fd6a5',
      'editorGutter.modifiedBackground': '#e6c27a',
      'editorGutter.deletedBackground': '#f1a9aa',
      'editorGutter.foldingControlForeground': '#e4e8ee',
      'editorError.foreground': '#ff9a9e',
      'editorWarning.foreground': '#f2c96a',
      'editorInfo.foreground': '#8ab8ff',
      'editorHint.foreground': '#c5ccd6',
      'editorError.border': '#00000000',
      'editorWarning.border': '#00000000',
      'editorInfo.border': '#00000000',
      'diffEditor.insertedTextBackground': '#8fd6a533',
      'diffEditor.removedTextBackground': '#f0a0a233',
      'diffEditor.insertedLineBackground': '#8fd6a51a',
      'diffEditor.removedLineBackground': '#f0a0a21a',
      'diffEditor.border': '#6b7380',
      'diffEditor.diagonalFill': '#ffffff40',
      'diffEditorGutter.insertedLineBackground': '#8fd6a533',
      'diffEditorGutter.removedLineBackground': '#f0a0a233',
      'editorWidget.background': '#000000',
      'editorWidget.foreground': '#ffffff',
      'editorWidget.border': '#ffffff',
      'editorWidget.resizeBorder': '#8ab8ff',
      'editorSuggestWidget.background': '#000000',
      'editorSuggestWidget.foreground': '#ffffff',
      'editorSuggestWidget.border': '#ffffff',
      'editorSuggestWidget.selectedBackground': '#6fa8ff52',
      'editorSuggestWidget.selectedForeground': '#ffffff',
      'editorSuggestWidget.highlightForeground': '#a3c7ff',
      'editorSuggestWidget.focusHighlightForeground': '#a3c7ff',
      'editorSuggestWidgetStatus.foreground': '#e4e8ee',
      'editorHoverWidget.background': '#000000',
      'editorHoverWidget.foreground': '#ffffff',
      'editorHoverWidget.border': '#ffffff',
      'editorHoverWidget.statusBarBackground': '#000000',
      'editorMarkerNavigation.background': '#000000',
      'editorMarkerNavigationError.background': '#2b0a0c',
      'editorMarkerNavigationWarning.background': '#2a1f00',
      'editorMarkerNavigationInfo.background': '#06183a',
      'editor.findMatchBorder': '#ffffff',
      'quickInput.background': '#000000',
      'quickInput.foreground': '#ffffff',
      'quickInputTitle.background': '#000000',
      'quickInputList.focusBackground': '#6fa8ff52',
      'quickInputList.focusForeground': '#ffffff',
      'quickInputList.focusIconForeground': '#ffffff',
      'list.hoverBackground': '#ffffff24',
      'list.hoverForeground': '#ffffff',
      'list.activeSelectionBackground': '#6fa8ff52',
      'list.activeSelectionForeground': '#ffffff',
      'list.inactiveSelectionBackground': '#ffffff2e',
      'list.inactiveSelectionForeground': '#ffffff',
      'list.focusBackground': '#6fa8ff52',
      'list.focusOutline': '#8ab8ff',
      'list.highlightForeground': '#a3c7ff',
      'input.background': '#000000',
      'input.foreground': '#ffffff',
      'input.border': '#b4bcc8',
      'input.placeholderForeground': '#c5ccd6',
      'inputOption.activeBackground': '#0d2247',
      'inputOption.activeBorder': '#8ab8ff',
      'inputOption.activeForeground': '#ffffff',
      'inputValidation.errorBackground': '#2b0a0c',
      'inputValidation.errorBorder': '#ff9a9e',
      'inputValidation.warningBackground': '#2a1f00',
      'inputValidation.warningBorder': '#f2c96a',
      'inputValidation.infoBackground': '#06183a',
      'inputValidation.infoBorder': '#8ab8ff',
      'dropdown.background': '#000000',
      'dropdown.foreground': '#ffffff',
      'dropdown.border': '#b4bcc8',
      'button.background': '#6fa8ff',
      'button.foreground': '#000000',
      'button.hoverBackground': '#8ab8ff',
      'badge.background': '#6fa8ff',
      'badge.foreground': '#000000',
      'scrollbar.shadow': '#00000000',
      'scrollbarSlider.background': '#ffffff99',
      'scrollbarSlider.hoverBackground': '#ffffffc2',
      'scrollbarSlider.activeBackground': '#ffffffeb',
      'minimap.background': '#000000',
      'minimap.selectionHighlight': '#6fa8ff52',
      'minimap.findMatchHighlight': '#ffd54a66',
      'minimap.errorHighlight': '#ff9a9e',
      'minimap.warningHighlight': '#f2c96a',
      'minimapSlider.background': '#ffffff33',
      'minimapSlider.hoverBackground': '#ffffff47',
      'minimapSlider.activeBackground': '#ffffff5c',
      'minimapGutter.addedBackground': '#8fd6a5',
      'minimapGutter.modifiedBackground': '#e6c27a',
      'minimapGutter.deletedBackground': '#f1a9aa',
      'editorOverviewRuler.border': '#00000000',
      'editorOverviewRuler.background': '#000000',
      'editorOverviewRuler.errorForeground': '#ff9a9e',
      'editorOverviewRuler.warningForeground': '#f2c96a',
      'editorOverviewRuler.infoForeground': '#8ab8ff',
      'editorOverviewRuler.addedForeground': '#8fd6a5',
      'editorOverviewRuler.modifiedForeground': '#e6c27a',
      'editorOverviewRuler.deletedForeground': '#f1a9aa',
      'editorOverviewRuler.findMatchForeground': '#ffd54a66',
      'editorOverviewRuler.selectionHighlightForeground': '#6fa8ff52',
      'editorOverviewRuler.bracketMatchForeground': '#6fa8ff66',
      'peekView.border': '#8ab8ff',
      'peekViewEditor.background': '#000000',
      'peekViewEditor.matchHighlightBackground': '#ffd54a66',
      'peekViewEditorGutter.background': '#000000',
      'peekViewResult.background': '#000000',
      'peekViewResult.fileForeground': '#ffffff',
      'peekViewResult.lineForeground': '#e4e8ee',
      'peekViewResult.matchHighlightBackground': '#ffd54a66',
      'peekViewResult.selectionBackground': '#6fa8ff52',
      'peekViewResult.selectionForeground': '#ffffff',
      'peekViewTitle.background': '#000000',
      'peekViewTitleLabel.foreground': '#ffffff',
      'peekViewTitleDescription.foreground': '#e4e8ee',
      'menu.background': '#000000',
      'menu.foreground': '#ffffff',
      'menu.selectionBackground': '#6fa8ff52',
      'menu.selectionForeground': '#ffffff',
      'menu.separatorBackground': '#6b7380',
      'menu.border': '#ffffff',
      contrastBorder: '#ffffff',
      contrastActiveBorder: '#8ab8ff',
      'list.activeSelectionBorder': '#ffffff',
      'list.inactiveSelectionBorder': '#ffffff',
      'list.hoverBorder': '#b4bcc8',
      'minimapSlider.border': '#b4bcc8',
    },
  },
};

/** Map the app theme id (html[data-theme]) to the Monaco theme name. */
export const monacoThemeFor = (theme: 'light' | 'dark' | 'hc-light' | 'hc-dark'): IncThemeName =>
  `inc-${theme}` as IncThemeName;
